@WebApi_HostAddress = http://localhost:5288

### 1. pobranie listy kontaktow - stronicowanie
GET {{WebApi_HostAddress}}/api/contacts?page=1&size=10
Accept: application/json

### 2. dodanie osoby
POST http://localhost:5288/api/contacts
Content-Type: application/json

{
  "firstName": "Patryk",
  "lastName": "Testowy",
  "email": "patryk@test.pl",
  "phone": "123456789",
  "position": "Student",
  "birthDate": "2002-05-10",
  "gender": 0,
  "employerId": "516A34D7-CCFB-4F20-85F3-62BD0F3AF271",
  "address": {
    "street": "Testowa 1",
    "city": "Krakow",
    "postalCode": "30-001",
    "country": "Poland",
    "type": 0
  }
}


### 3. pobranie osoby p oid
GET {{WebApi_HostAddress}}/api/contacts/4e362867-5c73-47e3-9fd3-83970786bfc9
Accept: application/json

### 4. edycja osoby po id
PUT {{WebApi_HostAddress}}/api/contacts/b4dcb17c-f875-43f8-9d66-36597895a466
Content-Type: application/json

{
  "firstName": "marcin",
  "lastName": "Kulak",
  "email": "jan@wsei.edu.pl",
  "phone": "999999999",
  "position": "Programista",
  "gender": 0,
  "status": 0
}

### 5. usunięcie po ID
DELETE {{WebApi_HostAddress}}/api/contacts/b308643e-154a-424e-b925-4f27d34f9330

### 6. test walidacji - błędny post
POST {{WebApi_HostAddress}}/api/contacts
Content-Type: application/json

{
  "firstName": "Adam"
}

### 7. dodanie osoby na test notatek
POST {{WebApi_HostAddress}}/api/contacts
Content-Type: application/json

{
  "firstName": "Kamil",
  "lastName": "Testowy",
  "email": "kamil@wsei.edu.pl",
  "phone": "555666777",
  "position": "Tester",
  "birthDate": "2000-05-10T00:00:00",
  "gender": 0
}

### 8. dodanie notaki do osoby
POST {{WebApi_HostAddress}}/api/contacts/4e362867-5c73-47e3-9fd3-83970786bfc9/notes
Content-Type: application/json

{
  "content": "nowa notka ef test"
}

### 9. pobranie notatek
GET {{WebApi_HostAddress}}/api/contacts/4e362867-5c73-47e3-9fd3-83970786bfc9/notes
Accept: application/json

### 10. handler test - nie ma osoby
POST {{WebApi_HostAddress}}/api/contacts/00000000-0000-0000-0000-000000000000/notes
Content-Type: application/json

{
  "content": "test not found"
}

### 11. usuniecie notatki
DELETE {{WebApi_HostAddress}}/api/contacts/1981917c-e7dd-4e1e-8ae9-d4375ada57eb/notes/dcaa06d6-1703-4e71-9341-be2a3d513323

### auth - login
POST http://localhost:5288/api/auth/login
Content-Type: application/json

{
  "email": "admin@crm.pl",
  "password": "Admin@123!"
}

### wejscie bez tokena -brak autory
GET http://localhost:5288/api/contacts?page=1&size=10
Accept: application/json

###  wejscie z tokenem jwt - dostep do secu endpoint
GET http://localhost:5288/api/contacts?page=1&size=10
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IkY1QkFERTE0LTZDQzgtNDJBMi05QTQ0LTk4NDJEQTJEOTI4MCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImFkbWluQGNybS5wbCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2dpdmVubmFtZSI6IkFkYW0iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zdXJuYW1lIjoiQWRtaW5pc3RyYXRvciIsImRlcGFydG1lbnQiOiJJVCIsInN0YXR1cyI6IjAiLCJqdGkiOiI3NjNjYTFjYS1mYmJkLTRkZTAtODM4ZS0xOGMwYjBjZDY2ZTEiLCJpYXQiOiIxNzc2ODExOTM4IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW5pc3RyYXRvciIsIm5iZiI6MTc3NjgxMTkzOCwiZXhwIjoxNzc2ODE1NTM4LCJpc3MiOiJJZGVpc0NybUFwaSIsImF1ZCI6IkNybUNsaWVudCJ9.o_7qXnxRLT7lkYhUTLwB7wAI4wZg9KnXeUB_oLQb5cE


### odczyt claims z tokena - dane zalogowanego uzytkoweniak
GET http://localhost:5288/api/auth/me
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IkY1QkFERTE0LTZDQzgtNDJBMi05QTQ0LTk4NDJEQTJEOTI4MCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImFkbWluQGNybS5wbCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2dpdmVubmFtZSI6IkFkYW0iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zdXJuYW1lIjoiQWRtaW5pc3RyYXRvciIsImRlcGFydG1lbnQiOiJJVCIsInN0YXR1cyI6IjAiLCJqdGkiOiI3NjNjYTFjYS1mYmJkLTRkZTAtODM4ZS0xOGMwYjBjZDY2ZTEiLCJpYXQiOiIxNzc2ODExOTM4IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW5pc3RyYXRvciIsIm5iZiI6MTc3NjgxMTkzOCwiZXhwIjoxNzc2ODE1NTM4LCJpc3MiOiJJZGVpc0NybUFwaSIsImF1ZCI6IkNybUNsaWVudCJ9.o_7qXnxRLT7lkYhUTLwB7wAI4wZg9KnXeUB_oLQb5cE

### odswiezenie tokenow - nowy accestoken + refreshtoken
POST http://localhost:5288/api/auth/refresh
Content-Type: application/json

{
  "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IkY1QkFERTE0LTZDQzgtNDJBMi05QTQ0LTk4NDJEQTJEOTI4MCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImFkbWluQGNybS5wbCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2dpdmVubmFtZSI6IkFkYW0iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zdXJuYW1lIjoiQWRtaW5pc3RyYXRvciIsImRlcGFydG1lbnQiOiJJVCIsInN0YXR1cyI6IjAiLCJqdGkiOiI3NjNjYTFjYS1mYmJkLTRkZTAtODM4ZS0xOGMwYjBjZDY2ZTEiLCJpYXQiOiIxNzc2ODExOTM4IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW5pc3RyYXRvciIsIm5iZiI6MTc3NjgxMTkzOCwiZXhwIjoxNzc2ODE1NTM4LCJpc3MiOiJJZGVpc0NybUFwaSIsImF1ZCI6IkNybUNsaWVudCJ9.o_7qXnxRLT7lkYhUTLwB7wAI4wZg9KnXeUB_oLQb5cE",
  "refreshToken": "51AM1NG08cPpzNIHPCKxryXxy44jCCIq0EzP+TUN3sZK2culNA07W7Ilzjn6QjFocjIfSfN12LQAAw2oc+5kzw=="
}

### wylogowanie uzytkownika auth api - uniewaznienie refrtesh tokena
POST http://localhost:5288/api/auth/revoke
Content-Type: application/json
Authorization: Bearer  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IkY1QkFERTE0LTZDQzgtNDJBMi05QTQ0LTk4NDJEQTJEOTI4MCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImFkbWluQGNybS5wbCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2dpdmVubmFtZSI6IkFkYW0iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zdXJuYW1lIjoiQWRtaW5pc3RyYXRvciIsImRlcGFydG1lbnQiOiJJVCIsInN0YXR1cyI6IjAiLCJqdGkiOiJjYjM0OGUzMC1lODFiLTQzNzYtYTYzMS0xYjVkZjkwNDdlMWEiLCJpYXQiOiIxNzc2ODEyMTIxIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW5pc3RyYXRvciIsIm5iZiI6MTc3NjgxMjEyMSwiZXhwIjoxNzc2ODE1NzIxLCJpc3MiOiJJZGVpc0NybUFwaSIsImF1ZCI6IkNybUNsaWVudCJ9.Hq8gg3kMU1XkrYxNNO4stzwui1eybBFP3FaeNOXRDUY


"URrcoaXc48A2xq1GKfJCGeIYpg9j6VqWvSSJVS8CtEwM4/UFz5hAwpU9dKDBDi3Hwujnq8XYjBbMrDcV6ZgoKw=="